echo "$(cat <<EOF
CREATE DATABASE $DB_NAME;
CREATE USER $DB_USERNAME WITH PASSWORD '$DB_PASSWORD';
ALTER USER $DB_USERNAME SET client_encoding TO 'utf8';
ALTER USER $DB_USERNAME SET default_isolation TO 'read committed';
ALTER USER $DB_USERNAME SET timezone TO 'UTC';
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME;
)"
