#!/bin/bash

logStart 'Django'

# Go into the Django project folder (generated by `django-admin.py startproject ...`)
cd $PROJECT_DJANGO_FOLDER_PATH

# Create an admin user (with prompts)
python3 manage.py createsuperuser

# Update the Database
python3 manage.py makemigrations
python3 manage.py migrate

# Generate/Copy the Static Files
python3 manage.py collectstatic

logEnd 'Django'
