#!/bin/bash

logStart 'Django'

# Add/Bind the IP Address value in Settings File
# - `''` immediately after `-i` is for without creating backup file (LINUX only, not Ubuntu)
sed -i -e "s/ALLOWED_HOSTS = \[\]/ALLOWED_HOSTS = \[ '$APP_IP_ADDR' \]/1" $DJ_SETTINGS_FILE_PATH

# Enable Virtual Env.
source $PROJECT_FOLDER_PATH/venv/bin/activate

# Go into the Django project folder (generated by `django-admin.py startproject ...`)
cd $PROJECT_DJANGO_FOLDER_PATH

# Update the Database
python manage.py makemigrations
python manage.py migrate

# Generate/Copy the Static Files
python manage.py collectstatic

# Create an admin user (with prompts) after DB done
python manage.py createsuperuser

# Exit the Virtual Env.
deactivate

logEnd 'Django'
